# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spider_ui.ui',
# licensing of 'spider_ui.ui' applies.
#
# Created: Thu Apr 11 14:08:44 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(514, 383)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/favicon-rr.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.loginFrame = QtWidgets.QFrame(Dialog)
        self.loginFrame.setGeometry(QtCore.QRect(130, 60, 261, 241))
        self.loginFrame.setAutoFillBackground(True)
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.loginFrame.setObjectName("loginFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.loginLabel = QtWidgets.QLabel(self.loginFrame)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.loginLabel.setFont(font)
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout.addWidget(self.loginLabel)
        self.emailInput = QtWidgets.QLineEdit(self.loginFrame)
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout.addWidget(self.emailInput)
        self.passwordInput = QtWidgets.QLineEdit(self.loginFrame)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.iCodeFrame = QtWidgets.QFrame(self.loginFrame)
        self.iCodeFrame.setVisible(False)
        self.iCodeFrame.setObjectName("iCodeFrame")
        self.iCodeBox = QtWidgets.QVBoxLayout(self.iCodeFrame)
        self.iCodeBox.setSpacing(6)
        self.iCodeBox.setContentsMargins(0, 0, 0, 0)
        self.iCodeBox.setObjectName("iCodeBox")
        self.iCodeImg = QtWidgets.QLabel(self.iCodeFrame)
        self.iCodeImg.setMinimumSize(QtCore.QSize(0, 50))
        self.iCodeImg.setObjectName("iCodeImg")
        self.iCodeBox.addWidget(self.iCodeImg)
        self.iCodeInput = QtWidgets.QLineEdit(self.iCodeFrame)
        self.iCodeInput.setObjectName("iCodeInput")
        self.iCodeBox.addWidget(self.iCodeInput)
        self.verticalLayout.addWidget(self.iCodeFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rememberCkb = QtWidgets.QCheckBox(self.loginFrame)
        self.rememberCkb.setObjectName("rememberCkb")
        self.horizontalLayout.addWidget(self.rememberCkb)
        self.loginBtn = QtWidgets.QPushButton(self.loginFrame)
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout.addWidget(self.loginBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mainFrame = QtWidgets.QFrame(Dialog)
        self.mainFrame.setGeometry(QtCore.QRect(10, 30, 491, 301))
        self.mainFrame.setVisible(False)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputPathInput = QtWidgets.QLineEdit(self.mainFrame)
        self.outputPathInput.setObjectName("outputPathInput")
        self.horizontalLayout_2.addWidget(self.outputPathInput)
        self.browserBtn = QtWidgets.QPushButton(self.mainFrame)
        self.browserBtn.setObjectName("browserBtn")
        self.horizontalLayout_2.addWidget(self.browserBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.userInput = QtWidgets.QLineEdit(self.mainFrame)
        self.userInput.setObjectName("userInput")
        self.verticalLayout_3.addWidget(self.userInput)
        self.startBtn = QtWidgets.QPushButton(self.mainFrame)
        self.startBtn.setObjectName("startBtn")
        self.verticalLayout_3.addWidget(self.startBtn)
        self.progressFrame = QtWidgets.QFrame(self.mainFrame)
        self.progressFrame.setVisible(False)
        self.progressFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressFrame.setObjectName("progressFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.progressFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.progressFrame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.progressFrame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_3.addWidget(self.progressFrame)
        self.copyright = QtWidgets.QLabel(Dialog)
        self.copyright.setGeometry(QtCore.QRect(20, 360, 471, 16))
        self.copyright.setObjectName("copyright")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "人人网备份工具-V1.0", None, -1))
        self.loginLabel.setText(QtWidgets.QApplication.translate("Dialog", "请登录", None, -1))
        self.emailInput.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "邮箱", None, -1))
        self.passwordInput.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "密码", None, -1))
        self.iCodeImg.setText(QtWidgets.QApplication.translate("Dialog", "TextLabel", None, -1))
        self.iCodeInput.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "请输入图中字符", None, -1))
        self.rememberCkb.setText(QtWidgets.QApplication.translate("Dialog", "记住我", None, -1))
        self.loginBtn.setText(QtWidgets.QApplication.translate("Dialog", "登录", None, -1))
        self.outputPathInput.setText(QtWidgets.QApplication.translate("Dialog", "output", None, -1))
        self.outputPathInput.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "输出路径", None, -1))
        self.browserBtn.setText(QtWidgets.QApplication.translate("Dialog", "浏览...", None, -1))
        self.userInput.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "输入用户ID，若空则获取本账号", None, -1))
        self.startBtn.setText(QtWidgets.QApplication.translate("Dialog", "开始", None, -1))
        self.copyright.setText(QtWidgets.QApplication.translate("Dialog", "Copyright©2019 by Frost Ming <a href=\"https://github.com/frostming/renren-dumps\">https://github.com/frostming/renren-dumps</a>", None, -1))

import resource_rc
